apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-app1-dev
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ammad.khalid@abc.com
    privateKeySecretRef:
      name: account-key-prod
    solvers:
      - http01:
          ingress:
            class: nginx